#!/usr/bin/with-contenv bash
set -euo pipefail

# apt mirror
if [ -n "${APT_MIRROR:-}" ] && [ -f /etc/apt/sources.list ]; then
    if grep -qoE "([a-z]{2}.)?archive.ubuntu.com|security.ubuntu.com" /etc/apt/sources.list; then
        sed -i -re "s/([a-z]{2}.)?archive.ubuntu.com|security.ubuntu.com/$APT_MIRROR/g" /etc/apt/sources.list
        apt-get update -qq
    fi
fi

# ubuntu
if [ -n "${INSTALL_APT_PKGS:-}" ] && [ -f /usr/bin/apt ]; then
    export DEBIAN_FRONTEND=noninteractive
    # apt-get update if never done during the past 24 hours
    [ ! -d /var/lib/apt/lists/partial ] && apt-get update -yqq
    [ -z "$(find -H /var/lib/apt/lists -maxdepth 0 -mtime -1)" ] && apt-get update -yqq
    echo "*** installing apt packages: ${INSTALL_APT_PKGS}"
    apt-get install -yqq --no-install-recommends \
        ${INSTALL_APT_PKGS} > /dev/null 2>&1
fi

# alpine
if [ -n "${INSTALL_APK_PKGS:-}" ] && [ -f /sbin/apk ]; then
    echo "*** installing apk packages: ${INSTALL_APK_PKGS}"
    apk add -q --no-cache \
        ${INSTALL_APK_PKGS} > /dev/null 2>&1
fi

# python
if [ -n "${INSTALL_PIP_PKGS:-}" ] && command -v pip3 >/dev/null 2>&1; then
    # effective as of pip v22.1
    export PIP_ROOT_USER_ACTION=ignore
    echo "*** installing pip packages: ${INSTALL_PIP_PKGS}"
    python3 -m pip -q install -U ${INSTALL_PIP_PKGS}
fi
