#!/usr/bin/with-contenv bash
set -euo pipefail

install_findmnt() {
    # Check for findmnt
    if ! command -v findmnt >/dev/null 2>&1; then
        if [ -f /sbin/apk ]; then
            apk add -q --no-cache findmnt
        fi
    fi
}

if [ -n "${WAIT_RCLONE_MNTS:-}" ]; then
    install_findmnt

    IFS='|' read -r -a WAIT_RCLONE_MNTS <<< "$WAIT_RCLONE_MNTS"
    for WAIT_RCLONE_MNT in "${WAIT_RCLONE_MNTS[@]}"; do
        # Loop until desired mount is found
        until [ "$(findmnt "${WAIT_RCLONE_MNT}" | grep fuse.rclone -c)" = "1" ]; do
            echo "ERROR: rclone mountpoint (${WAIT_RCLONE_MNT}) not found. Retrying in 30s ..."
            sleep 30
        done
    done
fi

if [ -n "${WAIT_MFS_MNTS:-}" ]; then
    install_findmnt

    IFS='|' read -r -a WAIT_MFS_MNTS <<< "$WAIT_MFS_MNTS"
    for WAIT_MFS_MNT in "${WAIT_MFS_MNTS[@]}"; do
        # Loop until desired mount is found
        until [ "$(findmnt "${WAIT_MFS_MNT}" | grep fuse.mergerfs -c)" = "1" ]; do
            echo "ERROR: mergerfs mountpoint (${WAIT_MFS_MNT}) not found. Retrying in 30s ..."
            sleep 30
        done
    done
fi

if [ -n "${WAIT_ANCHOR_DIRS:-}" ]; then
    IFS='|' read -r -a WAIT_ANCHOR_DIRS <<< "$WAIT_ANCHOR_DIRS"
    for WAIT_ANCHOR_DIR in "${WAIT_ANCHOR_DIRS[@]}"; do
        # Loop until desired dir is found
        until [ -d "${WAIT_ANCHOR_DIR}" ]; do
            echo "ERROR: directory (${WAIT_ANCHOR_DIR}) not found. Retrying in 30s ..."
            sleep 30
        done
    done
fi

if [ -n "${WAIT_ANCHOR_FILES:-}" ]; then
    IFS='|' read -r -a WAIT_ANCHOR_FILES <<< "$WAIT_ANCHOR_FILES"
    for WAIT_ANCHOR_FILE in "${WAIT_ANCHOR_FILES[@]}"; do
        # Loop until desired file is found
        until [ -f "${WAIT_ANCHOR_FILE}" ]; do
            echo "ERROR: file (${WAIT_ANCHOR_FILE}) not found. Retrying in 30s ..."
            sleep 30
        done
    done
fi
