name: buildx

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  schedule:
    - cron: "0 21 * * 5"

env:
  IMAGE_NAME: ghcr.io/by275/base

jobs:
  alpine:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        tag: [alpine, alpine3.16, alpine3.17, alpine3.18, alpine3.19]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Buildx and Push
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.tag }}/.
          file: ${{ matrix.tag }}/Dockerfile
          tags: |
            ${{ env.IMAGE_NAME }}:${{ matrix.tag }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
      -
        name: Send Notification
        uses: sarisia/actions-status-discord@v1
        if: failure()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          description: |
            ${{ env.IMAGE_NAME }}:${{ matrix.tag }}

  ubuntu:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        tag: [ubuntu, ubuntu20.04, ubuntu22.04, ubuntu24.04]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Buildx and Push
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.tag }}/.
          file: ${{ matrix.tag }}/Dockerfile
          tags: |
            ${{ env.IMAGE_NAME }}:${{ matrix.tag }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
      -
        name: Send Notification
        uses: sarisia/actions-status-discord@v1
        if: failure()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          description: |
            ${{ env.IMAGE_NAME }}:${{ matrix.tag }}
